ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.5.14
    hooks:
      - id: biome-check
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.40
    hooks:
      - id: pymarkdown
        files: ^((en|es|fr)/.*\.md|README\.md)$
