lang: en
locale: en_US
url: https://sustainable.open-contracting.org
google_analytics: G-L1NXBGRV3Q
search: true
breadcrumb_label: More pages
search_labels:
  search: Search
  no_results: No results found
  result: result
  results: results
  select: Select
  open: Open
  open_in_new_tab: Open in a new tab
destination: _site/en
exclude: [es, fr, scripts, "Export-*", README.md, LICENSE.md, biome.jsonc, "pa11y.*.js", package.json, "pnpm-*.yaml", pyproject.toml, uv.lock]
