lang: fr
locale: fr_FR
title: Les marchés publics durables et ouverts
url: https://achatdurable.open-contracting.org
google_analytics: G-GFLEM9K3JF
search: true
breadcrumb_label: Plus de pages
language_label: Langue
sidebar_label: Sommaire
table_scroll_label: Faites défiler pour en voir plus
expand_label: Tout déplier
collapse_label: Tout replier
pdf_label: "Télécharger le PDF (en anglais, %{size} Ko)"
pager_label: Pages précédente et suivante
previous_label: Précédent
next_label: Suivant
search_labels:
  search: Rechercher
  no_results: Aucun résultat
  result: résultat
  results: résultats
  select: Sélectionner
  open: Ouvrir
  open_in_new_tab: Ouvrir dans un nouvel onglet
destination: _site/fr
exclude: [en, es, scripts, README.md, LICENSE.md, biome.jsonc, build.mjs, knip.jsonc, "pa11y.*.js", package.json, "pnpm-*.yaml", pyproject.toml, uv.lock]
notion:
  hide_properties: true
