lang: es
locale: es_ES
url: https://sostenibilidad.open-contracting.org
google_analytics: G-GFLEM9K3JF
search: true
breadcrumb_label: Más páginas
language_label: Idioma
sidebar_label: Contenido
table_scroll_label: Desplácese para ver más
search_labels:
  search: Buscar
  no_results: No se encontraron resultados
  result: resultado
  results: resultados
  select: Seleccionar
  open: Abrir
  open_in_new_tab: Abrir en una pestaña nueva
destination: _site/es
exclude: [en, fr, scripts, "Export-*", README.md, LICENSE.md, biome.jsonc, build.mjs, knip.jsonc, "pa11y.*.js", package.json, "pnpm-*.yaml", pyproject.toml, uv.lock]
notion:
  hide_properties: true
