lang: fr
locale: fr_FR
url: https://achatdurable.open-contracting.org
google_analytics: G-GFLEM9K3JF
search: true
breadcrumb_label: Plus de pages
search_labels:
  search: Rechercher
  no_results: Aucun résultat
  result: résultat
  results: résultats
  select: Sélectionner
  open: Ouvrir
  open_in_new_tab: Ouvrir dans un nouvel onglet
destination: _site/fr
exclude: [en, es, scripts, "Export-*", README.md, LICENSE.md, biome.jsonc, "pa11y.*.js", package.json, "pnpm-*.yaml", pyproject.toml, uv.lock]
notion:
  hide_properties: true
